Tracker:AddLocations("locations/Amadeus Necropolis.json")
Tracker:AddLocations("locations/Astrom.json")
Tracker:AddLocations("locations/Campanula.json")
Tracker:AddLocations("locations/Dusken Tanis.json")
Tracker:AddLocations("locations/Melm.json")
Tracker:AddLocations("locations/Misc.json")
Tracker:AddLocations("locations/Request Memos.json")
Tracker:AddLocations("locations/Rosatempus Memoria.json")
Tracker:AddLocations("locations/Umbra.json")
Tracker:AddLocations("locations/Unclean Ornit.json")
Tracker:AddLocations("locations/Verdant Phenom.json")
Tracker:AddLocations("locations/Overworld.json")
